{% set version = "2.16.0" %}

package:
  name: dataclasses-jsonschema
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/dataclasses-jsonschema/dataclasses-jsonschema-{{ version }}.tar.gz
  sha256: effb0c73db30a537a962da75c4f35b94a5b1b7c1b17806b1ef74aed8e0aa2768

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - pytest-runner
    - python {{ python_min }}
    - setuptools-scm
    - setuptools
  run:
    - dataclasses
    - jsonschema
    - python >={{ python_min }},<3.10
    - python-dateutil
    - typing-extensions

test:
  source_files:
    - tests
  imports:
    - dataclasses_jsonschema
  commands:
    - pip check
    - coverage run --source=dataclasses_jsonschema --branch -m pytest tests -vv --tb=long --color=yes
    - coverage report --show-missing --skip-covered --fail-under=91
  requires:
    - apispec
    - apispec-webframeworks
    - flask
    - pip
    - pytest-cov
    - pytest-ordering
    - python-fastjsonschema
    - python {{ python_min }}

about:
  home: https://github.com/s-knibbs/dataclasses-jsonschema
  summary: JSON schema generation from dataclasses
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
