{% set version = "2.16.0" %}

package:
  name: dataclasses-jsonschema
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/dataclasses-jsonschema/dataclasses-jsonschema-{{ version }}.tar.gz
  sha256: effb0c73db30a537a962da75c4f35b94a5b1b7c1b17806b1ef74aed8e0aa2768

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - pytest-runner
    # TODO: remove pin after https://github.com/s-knibbs/dataclasses-jsonschema/issues/181
    - python {{ python_min }}
    - setuptools-scm
  run:
    - dataclasses
    - jsonschema
    - python >={{ python_min }},<3.10
    - python-dateutil
    - typing-extensions

test:
  source_files:
    - tests
  imports:
    - dataclasses_jsonschema
  commands:
    - pip check
    - pytest tests -vv --cov dataclasses_jsonschema --cov-report=term-missing:skip-covered --cov-fail-under=91 --no-cov-on-fail
  requires:
    - apispec
    - apispec-webframeworks
    - flask
    - pip
    - pytest-cov
    - pytest-ordering
    - python-fastjsonschema
    - python {{ python_min }}

about:
  home: https://github.com/s-knibbs/dataclasses-jsonschema
  summary: JSON schema generation from dataclasses
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
